### ISSUE TITLE
支持 OneBot还是CQ码？

### ISSUE THREAD

**Issue by jiangyin14** [tangsu99/FSP-ChatBridgeVelocity#1]
本插件支持的是OneBot协议还是CQ码（go-cqhttp中post-format的string还是array）？
在新的QQ机器人技术中，OneBot被广泛应用而CQ码已被淡化。

**Comment by tangsu99** [comment]
并不是CQ码
使用的[go-cq-http](https://github.com/Mrs4s/go-cqhttp)
![图片](https://github.com/tangsu99/FSP-ChatBridgeVelocity/assets/49725418/7676d081-0a65-4a87-bb96-af3fda1f397d)
### 然而
![图片](https://github.com/tangsu99/FSP-ChatBridgeVelocity/assets/49725418/d0850267-1b6f-4c35-80c7-8a571d0fe87d)
